show databases;
use hr;
show tables;
/*
data query language (DQL)
SELECT - COLUMN NAME
FROM - TABLE NAME
WHERE - CONDITION BEFORE GROUPING DATA 
GROUP BY  - TO GROUP THE DATA
HAVING - CONDITION AFTER GROUPING DATA
ORDER BY - SORTING THE DATA IN AN ORDER 

*/
 -- SELECTING ALL COLUMN FROM THE TABLE 
 SELECT *FROM EMPLOYEES;
 -- SELECT SINGLE COLUMN:
 SELECT EMPLOYEE_ID FROM EMPLOYEES;
 -- MULTIPLE COLUMNS:
 SELECT EMPLOYEE_ID, FIRST_NAME
 FROM EMPLOYEES;
 -- EMP FROM WORKING IN DEP 50:
 SELECT *
 FROM EMPLOYEES
 WHERE DEPARTMENT_ID IN (50,60,70,80);
 -- FECTCH EMP EARN MORE THAN 5K
 SELECT *
 FROM EMPLOYEES
 WHERE SALARY>5000;
 -- FETCH EMP EARN BETWEEN 5K TO 10K
 SELECT *
 FROM EMPLOYEES
 WHERE SALARY BETWEEN 5000 AND 10000;
 -- FETCH WORKS IN DEPT 50 AND EARN MORE 5K
 SELECT *
 FROM EMPLOYEES
 WHERE DEPARTMENT_ID=50 AND SALARY>5000;
 SELECT EMPLOYEE_ID,DEPARTMENT_ID,
 FIRST_NAME,SALARY
 FROM EMPLOYEES
 WHERE DEPARTMENT_ID=50 OR SALARY>5000;
 
 SELECT *
 FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NOT NULL;
 
 SELECT*
 FROM EMPLOYEES
 WHERE MANAGER_ID IS NULL;
 SELECT distincT DEPARTMENT_ID 
 FROM EMPLOYEES;
 SELECT EMPLOYEE_ID, FIRST_NAME
 FROM EMPLOYEES
 WHERE FIRST_NAME LIKE 'J%';
SELECT EMPLOYEE_ID, FIRST_NAME
 FROM EMPLOYEES
 WHERE FIRST_NAME LIKE 'A%';
 SELECT EMPLOYEE_ID, FIRST_NAME
 FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '%O%O';
